<a href="https://colab.research.google.com/github/ShahriarParib/ML-Related-Codes/blob/main/Mini_Batch_Gd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [2]:
X,y=load_diabetes(return_X_y=True)


In [3]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [4]:
reg=LinearRegression()

In [5]:
reg.fit(X_train,y_train)

LinearRegression()

In [6]:
reg.coef_
reg.intercept_

np.float64(151.88331005254167)

In [7]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [8]:
y_pred=reg.predict(X_test)

In [9]:
r2_score(y_test,y_pred)

0.4399338661568968

In [10]:
import random

In [36]:
class MBGDregressor:
  def __init__(self,batch_size,learning_rate,epochs):
    self.lr=learning_rate
    self.epochs=epochs
    self.coef_ =None
    self.intercept_ =None
    self.batch_size=batch_size

  def fit(self,X_train,y_train):
    self.intercept_=0
    self.coef_=np.ones(X_train.shape[1])
    for i in range (self.epochs):
      for j in range(int(X_train.shape[0]/self.batch_size)):
        idx=random.sample(range(X_train.shape[0]),self.batch_size)
        y_hat=np.dot(X_train[idx],self.coef_)+self.intercept_
        intercept_der=-2*np.mean(y_train[idx]-y_hat)
        self.intercept_=self.intercept_-(self.lr*intercept_der)
        error = y_train[idx]- y_hat
        coef_der=-2*np.dot(error,X_train[idx])/X_train[idx].shape[0]
        self.coef_=self.coef_-(self.lr*coef_der)
    print(self.intercept_,self.coef_)
  def predict(self,X):
    return np.dot(X,self.coef_)+self.intercept_


In [54]:
mbgdr=MBGDregressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=200)

In [55]:
mbgdr.fit(X_train,y_train)

155.75294958863643 [  62.02689192  -24.81222871  261.52250289  193.23527245   37.54576165
    8.16408172 -143.38987247  124.12263187  245.04402906  120.17090195]


In [56]:
y_pred=mbgdr.predict(X_test)

In [57]:
r2_score(y_test,y_pred)

0.3964713639957832

In [59]:
from sklearn.linear_model import SGDRegressor

In [60]:
sgd=SGDRegressor(learning_rate='constant',eta0=0.1)

In [62]:
batch_size=35
for i in range(100):
  idx=random.sample(range(X_train.shape[0]),batch_size)
  sgd.partial_fit(X_train[idx],y_train[idx])


In [63]:
sgd.coef_

array([  51.27794932,  -56.98719969,  351.50845461,  264.6806806 ,
          2.86200461,  -38.84719168, -171.53501428,  120.71533412,
        301.31223404,  112.48074447])

In [64]:
sgd.intercept_

array([148.59758142])

In [67]:
y_pred=sgd.predict(X_test)

In [68]:
r2_score(y_test,y_pred)

0.42967949704802333